imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
use_small_heuristics = "Max"
